
const types = {
    GET_ERRORS: 'GET_ERRORS',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    GET_PROFILE: 'GET_PROFILE',
    PROFILE_LOADING: 'PROFILE_LOADING',
    CLEAR_PROFILE: 'CLEAR_PROFILE'
}

export default types;